# Generated by Django 2.2.10 on 2020-02-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_auto_20200214_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='body',
            new_name='content',
        ),
    ]
