# Generated by Django 2.2.10 on 2020-02-14 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0004_auto_20200215_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, default=0, related_name='like_user_set', through='internal.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
