# Generated by Django 2.2.10 on 2020-02-16 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internal', '0006_auto_20200215_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_work', models.CharField(max_length=100)),
                ('piro_no', models.PositiveIntegerField()),
                ('history', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
