# Generated by Django 2.2.10 on 2020-02-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0007_infobook'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
