# Generated by Django 2.2.10 on 2020-02-18 03:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0010_auto_20200218_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='내용'),
        ),
    ]
