# Generated by Django 2.2.10 on 2020-02-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_type',
            field=models.CharField(default='qna', max_length=250),
            preserve_default=False,
        ),
    ]
