# Generated by Django 2.2.10 on 2020-02-17 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import infoboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=infoboard.models.Files.date_upload_to)),
                ('filename', models.CharField(max_length=100)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoboard.Info')),
            ],
        ),
    ]
